### ISSUE TITLE
Deploy basic site

### ISSUE THREAD

**Issue by NExtremadouro** [NuriaExtremadouro/solar-system#1]
- [x] Find simple deployment tool.
- [x] Set it up.

**Comment by NuriaExtremadouro** [comment]
For now this will do:

- Using GitHub Pages.
- Made the repo public for that (also enables a bunch of extra stuff).
- To use src/index.js added the gh-pages dep, a deploy script and executed it. Now it uses the branch gh-pages to load the site.
